name: my_environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - face_recognition
  - opencv-python
  - dlib
  # Add any other dependencies your project needs

conda env update -f environment.yml
